nint1 = int (input ("insira um número inteiro ="))
nint2 = int (input ("insira um outro número inteiro ="))
nreal = float (input ("insira um número real ="))
calc1 = (nint1*2)*(nint2/2)
calc2 = (nint1*3)+(nreal)
calc3 = (nreal*nreal*nreal)
print ("o produto do dobro do primeiro com a metade do segundo é igual a = " + str(calc1))
print ("A soma do triplo do primeiro com metade do segundo é = " + str(calc2))
print ( "o triplo do terceiro é igual a = " + str(calc3))